# Generated by Django 3.2.11 on 2022-01-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='shipping.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='BadCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Provide reason why given ingredients can not be combined?')),
                ('ingredient_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_a', to='shipping.ingredient')),
                ('ingredient_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_b', to='shipping.ingredient')),
            ],
            options={
                'unique_together': {('ingredient_A', 'ingredient_B')},
            },
        ),
    ]
